alert('from javascript.js');
console.log(NaN == NaN);
console.log(NaN === NaN);
console.log(isNaN(100));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log(isNaN('abcd'));
console.log('------\\u------');
console.log('A' === '\u0041');
console.log('ABCDEFG'.length);
console.log('c'+'a'+'t' === 'cat');
